// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAwDil5KIk-6Qv-ufYTwt7kllqv5vH_Hk',
    appId: '1:54303097993:web:75ebfd979c0acf162fb258',
    messagingSenderId: '54303097993',
    projectId: 'gcufanbase',
    authDomain: 'gcufanbase.firebaseapp.com',
    storageBucket: 'gcufanbase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr8U6NWoGLbsSteJ8oNGCZXY-axJiHd9Y',
    appId: '1:54303097993:android:61ea6cdf3666fdbb2fb258',
    messagingSenderId: '54303097993',
    projectId: 'gcufanbase',
    storageBucket: 'gcufanbase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_tadNDPpv9y82EPh2QO5Zjp9FpNrdK5o',
    appId: '1:54303097993:ios:74cfef3f1e5c0c422fb258',
    messagingSenderId: '54303097993',
    projectId: 'gcufanbase',
    storageBucket: 'gcufanbase.appspot.com',
    iosBundleId: 'com.example.theFinalApp',
  );
}
